using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace grooming.Models
{
    public class GroomingOffer
    {
        public string Style { get; set; }
        public Hairdresser Hairdresser { get; set; }

        public static GroomingOffer[] Current =
        {
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Olga")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Olga")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Olga")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Olga")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Olga")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Olga")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Olga")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Konstantin")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Konstantin")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Konstantin")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Konstantin")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Konstantin")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Konstantin")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Konstantin")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Evgeny")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Evgeny")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Evgeny")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Evgeny")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Evgeny")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Evgeny")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Evgeny")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Alexander")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Alexander")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Alexander")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Alexander")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Alexander")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Alexander")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Alexander")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Irina")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Irina")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Irina")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Irina")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Irina")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Irina")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Irina")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Ilia")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Ilia")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Ilia")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Ilia")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Ilia")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Ilia")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Ilia")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Ksenia")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Ksenia")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Ksenia")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Ksenia")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Ksenia")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Ksenia")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Ksenia")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Oksana")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Oksana")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Oksana")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Oksana")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Oksana")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Oksana")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Oksana")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Svetlana")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Svetlana")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Svetlana")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Svetlana")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Svetlana")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Svetlana")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Svetlana")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Tatiana")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Tatiana")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Tatiana")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Tatiana")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Tatiana")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Tatiana")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Tatiana")},
            new GroomingOffer { Style = "Neaten" },
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Olga")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Olga")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Olga")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Olga")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Olga")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Olga")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Olga")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Konstantin")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Konstantin")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Konstantin")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Konstantin")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Konstantin")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Konstantin")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Konstantin")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Evgeny")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Evgeny")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Evgeny")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Evgeny")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Evgeny")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Evgeny")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Evgeny")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Alexander")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Alexander")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Alexander")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Alexander")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Alexander")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Alexander")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Alexander")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Irina")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Irina")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Irina")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Irina")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Irina")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Irina")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Irina")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Ilia")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Ilia")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Ilia")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Ilia")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Ilia")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Ilia")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Ilia")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Ksenia")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Ksenia")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Ksenia")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Ksenia")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Ksenia")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Ksenia")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Ksenia")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Oksana")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Oksana")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Oksana")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Oksana")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Oksana")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Oksana")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Oksana")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Svetlana")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Svetlana")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Svetlana")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Svetlana")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Svetlana")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Svetlana")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Svetlana")},
            new GroomingOffer { Style = "Neaten", Hairdresser = new Hairdresser("Tatiana")},
            new GroomingOffer { Style = "The Lamb Cut", Hairdresser = new Hairdresser("Tatiana")},
            new GroomingOffer { Style = "The Lion Cut", Hairdresser = new Hairdresser("Tatiana")},
            new GroomingOffer { Style = "The Puppy Cut", Hairdresser = new Hairdresser("Tatiana")},
            new GroomingOffer { Style = "The Schnauzer Cut", Hairdresser = new Hairdresser("Tatiana")},
            new GroomingOffer { Style = "The Teddy Bear Cut", Hairdresser = new Hairdresser("Tatiana")},
            new GroomingOffer { Style = "The Practical Top-Knot", Hairdresser = new Hairdresser("Tatiana")}
        };
    }
}
